### ISSUE TITLE
notify url returns 404 when payment success after first payment fail

### ISSUE THREAD

**Issue by sdechomets** [FLUX-SE/SyliusPayumMoneticoPlugin#24]
Hello,

Monetico payment interface allow you to retry a payment when an a attempt fail. The "canceled" first attempt is sent to notify url, and is correctly saved as an error. The second attempt (with the same payment ID) is sent to notify url but it returns a 404.
Actually, the query attempt to find a payment record with state =PaymentInterface::STATE_NEW but the payment is not new anymore after the first return.
May you have an eye on this plz and tell me how to bypass this trouble ?

Thx

**Comment by Prometee** [comment]
Hello @sdechomets,

I'm not able to reproduce your issue, can you check that the `reference` (available on the Monetico Payment page) is the right `reference` searched by the notify URL ?

**Comment by sdechomets** [comment]
The reference is good, the first attempt is correctly sent to the site. You have to notice that the second attempt must be done WITHOUT leaving the payment interface. If you return to site and retry, it's ok, because when you return to site, a new payment record is created in the database with "new" status.
If you retry a payment when monetico suggest it "Faire un nouvel essai de paiement" (in french :-)), no new record is created. The payment is in "failed" status and is not updatable when the second payment occur (and is valid)

**Comment by Prometee** [comment]
I see what you mean, it'a apparently a new feature I didn't know about.

The thing is the state machine won't allows to set a `Payment` as  paid if it's canceled.
I guess the only way to fix this is to create a new Sylius `Payment` if the controller found a canceled payment.

**Comment by Prometee** [comment]
@sdechomets I make a new branch to test what is needed, can you try it within your test environment because I have some trouble with my test site (long story short we stop using Monetico and our notify URL is no more available).

Here is the composer command to test it :

```bash
composer require flux-se/sylius-payum-monetico-plugin:dev-new-payment-attempt
```

**Comment by sdechomets** [comment]
Hello, 

Many thx, I'm gonna try it, I'll keep you informed

**Comment by sdechomets** [comment]
It's quite good but not good enough :-). A new payment is correctly created when first payment failed BUT this new payment has no "details", that means, it has no reference. So when monetico try to update this new payment it can not find it by the reference.
Is it possible to save the reference of the monetico transaction in the new created payment (same as the marked as failed one) ?

**Comment by Prometee** [comment]
@sdechomets thank you for testing it.

Can you tell me what is the payment states of all order payments in the database when the second notify is reaching this line : https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/new-payment-attempt/src/Controller/NotifyController.php#L75 ?

To answer your question the details of the new payment is set with the old one here : https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/new-payment-attempt/src/Controller/NotifyController.php#L120

**Comment by sdechomets** [comment]
When the second notify is reaching L75, there's only 1 payment record with the good reference,and this is the one marked as "failed". The payment with "new" status has no details.
I was writing I saw L120 should do the job when I read your answer :-) but in fact it does not. In the database for the payment with state "new" there's no details it's an empty array []. Maybe you have to "save" it after setDetails L120 ?

**Comment by Prometee** [comment]
Saving it is useless because no sql query is done by Payum until Payum processes are done (with very strict conditions) : https://github.com/Payum/Payum/blob/master/src/Payum/Core/Extension/StorageExtension.php, and after all Payum processes Sylius will trigger the State Machine to save all `Order` related entities to the database.

I think I have to get this empty `Payment` (state `new`) instead of trying to create a new `Payment` (state `cart`).

Can you update your code and re-test it ? I pushed the modification to the branch :

```bash
composer up flux-se/sylius-payum-monetico-plugin
```

**Comment by Prometee** [comment]
@sdechomets I just pushed again, missing ")"... sorry !

**Comment by Prometee** [comment]
@sdechomets I was able to test te notify with a BEHAT scenario, so now it should work.

**Comment by Prometee** [comment]
@sdechomets I merge the PR into master, can you test it by doing this, and I will make a new release :

```bash
composer require flux-se/sylius-payum-monetico-plugin:dev-master
```

**Comment by sdechomets** [comment]
Hello, good job, it works ! There's is still a thing a little bit confusing : when you return to site after second valid payment you are redirected to the payment page (and not the command confirmation page) with a message displayed : "info : Le paiement a échoué". Everything else is ok, but the user may have doubt about the payemnt status even if its command is ok.

**Comment by Prometee** [comment]
@sdechomets arf ! It's tricky this time... The capture url used to get back to Sylius is pointing to the `Token` which as been used to cancel the first `Payment`. I will try to change the `Token` `details` to link it to the right last `Payment`.

**Comment by Prometee** [comment]
@sdechomets I was able to get my CGI call up again and I updated the master branch to fix this last issue.
Can you test it one last time to be sure everything is ok ?

**Comment by sdechomets** [comment]
Looks like it's working, you rock !
I read you do not work with Monetico anymore, does that means that you won't continue to support this specific bundle ?

**Comment by Prometee** [comment]
I try to support it whenever I don't used it anymore, the Payum library is made by [Ekyna](https://github.com/ekyna/PayumMonetico) so only specific issues with Sylius are supported here.
This issue should be handle by Ekyna, but the way they are handling `Notify` can't be able to do what I code here to fix this issue.

I'll release a new version, thank you for reporting this issue 😉
