### ISSUE TITLE
monetico 404 on second payment attempt

### ISSUE THREAD

**Issue by devozanges** [FLUX-SE/SyliusPayumMoneticoPlugin#26]
Hello,
I have a store that sells products worth about 1500€. Some payments go through very well, when it's a first attempt.
However, sometimes the payment may be rejected by the bank because the limit of the payment card is exceeded. So the customer makes the necessary and returns to pay once the modification made on the ceiling.
**This is when I have a problem.** On the Monetico side it works, but **the POST payment notification takes a 404 when it is an attempt that comes after a rejected attempt**.
I have no idea how to handle this problem. Does anyone have a clue?
thanks
![image](https://user-images.githubusercontent.com/15364311/174565130-014731d9-ec5a-4541-a510-5e982630c4ff.png)

**Comment by Prometee** [comment]
Hello @devozanges, this behaviour is normally covered by this plugin.
There is two cases :

1. The client fail paying by card and staying on the Monetico portal will retry with an other card and succeeeded. (BeHat test : https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/master/features/shop/paying_with_monetico_during_checkout.feature#L55-L63)
2. The client fail paying by card and go back to the shop to retry it another time. (BeHat test : https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/master/features/shop/paying_with_monetico_during_checkout.feature#L33-L41)

Then if you get a 404 this means the [controller](https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/master/src/Controller/NotifyController.php#L78-L86) is not able to retrieve the payment reference within the payload given by Monetico. This can only happen if the `reference` has been renewed within the Sylius `Payment` entity.
Do you recently change something on the [ReferenceProvider](https://github.com/FLUX-SE/SyliusPayumMoneticoPlugin/blob/master/src/Provider/ReferenceProvider.php) ?

**Comment by Prometee** [comment]
@devozanges can you check if you are using the latest version of this plugin, the last fixed issue was similar to the one you have.

**Comment by devozanges** [comment]
@Prometee Ok I am not the creator of this store but I see that the content of my `NotifyController` does not correspond to the release `1.1.1` so I think the problem will leave us when I will update, if I can do it, I do not know yet if there are technical constraints...🙄
Thanks a lot for your reactivity 🙏💪

**Comment by Prometee** [comment]
@devozanges youre welcome 😉
